### ISSUE TITLE
Change avatar dynamically

### ISSUE THREAD

**Issue by 1Map** [derlans/vue-avatar-upload#2]
I have a vue 3 app.

I have a data value (Base64 string) that changes dynamically in code.

`data:image/png;base64,xxxx`

How can I set the avatar property to the base64 string (**and nor a url**) before the Avatar Editor opens?

Seems that avatar property is only getting set once the component setup.

I have tried:

```
<VueAvatarUpload
      v-show="showAvatarSelector"
      :avatar="this.selectedAvatar"
      lang="en"
      width="200"
      height="200"
      selectSize="200"
      previewSize="200"
/>
```

But even if I change this.selectedAvatar to the new Base64 string, it still does not show

**Comment by derlans** [comment]
In the previous code, props.avatar was not responsive, and in the latest version, I fixed this issue

**Comment by 1Map** [comment]
Thanks working 100%.  How can I reset the image position and zoom when I re-open my component?  Like avatar property, is width/height/top/left also dynamic properties, in other words watches?

**Comment by derlans** [comment]
Currently, resetting these properties outside of the component is not supported. Width/height/top/left are not dynamic properties. I recommend adding a key to the component and updating the key when these properties need to be recharged. This may result in some performance loss, but there is currently no other way to do so

**Comment by 1Map** [comment]
Thanks, I am not so clued up with vue.  Will apreciate it if you can maybe show me a small sample of how this can be done.

**Comment by derlans** [comment]
## [codesandbox](https://codesandbox.io/p/github/derlans/vue-avatar-upload/master?workspace=%257B%2522activeFilepath%2522%253A%2522%252Fpreview%252FApp.vue%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clg88ugpd000x3n6jkshxocy6%2522%253A%257B%2522key%2522%253A%2522clg88ugpd000x3n6jkshxocy6%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clg896gs500ga3n6jnlvlsznz%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clg88ugpd000x3n6jkshxocy6%2522%252C%2522spacesOrder%2522%253A%255B%2522clg88ugpd000x3n6jkshxocy6%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)
you can see the demo preview/APP.vue
```
---script

const key = ref(0)

---template

<AvatarUpload :key="key" v-bind="Props" @custom-request="handelUpload" @close="handelClose" @error="handelErr" @success="handelSuccess" />
<div style="display: flex;justify-content: center;">
    <NButton type="success" @click="key++">
          update Props
    </NButton>
</div>

**Comment by 1Map** [comment]
Thanks, 100% working now.  You can close this ticket.
