### ISSUE TITLE
Disable resizing and moving of circle

### ISSUE THREAD

**Issue by 1Map** [derlans/vue-avatar-upload#3]
How can I:

1) Have the white circle at a fixed position
2) Only zoom and drag the image
3) Disable dragging and sizing of circle

For example (image below).  I want the circle to be fixed at 200px x 200px and in the middle.  Then I do not want the user to size and drag the circle (Want to force the end-image to be 200x200).  User must only be able to drag and size (zoom) the background image.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/1152458/230716310-a4f97891-1cdc-4afa-b4f6-f3863998d7a0.png">

**Comment by derlans** [comment]
Thank you for your suggestion. In the latest version, I have added Prop.disableSelect to control it

**Comment by 1Map** [comment]
Thanks that was very fast.  Working 100% on my side.  Only thing is to disable the css styles on the circle as well as the small white dot when disableSelect is true.  Otherwise 100%

**Comment by derlans** [comment]
You're right. I forgot this detail and I will fix it as soon as possible
